models:
  - name: products
    description: "This table contains product information."
    columns:
      - name: bronze_ingestion_id
        description: "The unique identifier from ingestion."
        tests:
          - not_null
          - unique
      - name: id
        description: "The unique identifier for the product."
        tests:
          - not_null
          - unique
      - name: name
        description: "The name of the product."
        tests:
          - not_null
      - name: category
        description: "The category of the product."
        tests:
          - not_null
      - name: price
        description: "The price of the product."
        tests:
          - not_null
      - name: created_at
        description: "The timestamp when the product was created."
        tests:
          - not_null
      - name: updated_at
        description: "The timestamp when the product was last updated."
        tests:
          - not_null